# Generated by Django 5.0.6 on 2024-06-14 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_booking_dateofreservation_alter_booking_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='roomNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
